# Generated by Django 4.1.6 on 2023-02-10 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iap',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='read_excel.basemodel')),
                ('site_id', models.IntegerField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('order_id', models.IntegerField(max_length=100)),
                ('purchase_id', models.IntegerField(max_length=100)),
                ('csm_name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('macaddr', models.CharField(max_length=100)),
            ],
            bases=('read_excel.basemodel',),
        ),
    ]
