# Generated by Django 4.1.6 on 2023-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_excel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iap',
            name='basemodel_ptr',
        ),
        migrations.AlterField(
            model_name='iap',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
