# Generated by Django 4.1.6 on 2023-02-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_excel', '0002_remove_iap_basemodel_ptr_alter_iap_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iap',
            name='order_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
